### ISSUE TITLE
zzebra83 - updateFloatingDebt is not called before fixed pool withdrawal operations

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-interest-rate-model-judging#134]
zzebra83

medium

# updateFloatingDebt is not called before fixed pool withdrawal operations

## Summary

In Market.sol, The updateFloatingDebt function is not called by the withdrawAtMaturity before checking whether the withdraw operation is permissible under current market liquidity. This means that stale values for floating debt and assets will be used causing withdrawal from fixed pool to potentially proceed even though it will be detrimental to overall pool liquidity. 

## Vulnerability Detail

The  updateFloatingDebt plays a crucial role of ensuring the markets floating debt and assets are updated accordingly before any operation proceeds.

    https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Market.sol#L888C1-L896C7

It factors in the amount of time since the last update, the current interest rate, and determines the additional debt generated by interest to be added to the floating debt and assets of the market. This is why its called before all key  market operations, including:

1. before borrowing from fixed pool via borrowAtMaturity -> https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Market.sol#L302C1-L302C49
2. before borrowing from floating pool -> https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Market.sol#L150C1-L150C45.
3. Before repaying and refunding from floating pool via noTransferRefund -> https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Market.sol#L211C1-L211C45
4. before withdrawing from floating pool via beforeWithdraw hook -> https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Market.sol#L700C1-L700C45

However it is not called by the withdrawAtMaturity function which will withdraw assets supplied to the fixed pool. 

    https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Market.sol#L381C1-L389C6

The code above in withdrawAtMaturity checks whether the withdraw operation is permitted by making sure that:

    newFloatingBackupBorrowed + floatingDebt > floatingAssets

However the call to update floating debt is not triggered before the protocol liquidity check, so potentially the condition will use stale values for floating debt and floating assets. This can cause fixed pool withdrawals to succeed even though they can cause  newFloatingBackupBorrowed + floatingDebt to be more than the markets floating assets, undermining the liquidity of the market.

Compare this with a similar liquidity check in borrowAtMaturity but with the correct update before proceeding with check:

    https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Market.sol#L302C1-L306C60

## Impact

The missing update to floating debt means withdrawals from fixed pools can cause the overall liquidity position of the market to become at risk.

## Tool used

Manual Review

## Recommendation

        {
      // remove the supply from the fixed rate pool
      uint256 newFloatingBackupBorrowed = floatingBackupBorrowed +
        pool.withdraw(
          FixedLib.Position(position.principal, position.fee).scaleProportionally(positionAssets).principal
        );
      // @audit ensures floating debt and assets updated before checking protocol liquidity
       depositToTreasury(updateFloatingDebt());
      if (newFloatingBackupBorrowed + floatingDebt > floatingAssets) revert InsufficientProtocolLiquidity();
      floatingBackupBorrowed = newFloatingBackupBorrowed;
      depositToTreasury(updateFloatingDebt());
    }

As seen above, ensure the call to is made to updateFloatingDebt  before checking protocol liquidity.

**Comment by genesiscrew** [comment]
Hi @santipu03! The impact of new debt on floating assets and floating debt is not equal. The treasury fee is based off the new debt, and that is subtracted off the floating assets. So the condition can evaluate to false instead of true.

**Comment by santipu03** [comment]
The treasury fee is ultimately added to the floating assets on `depositToTreasury`, so the final ratio of `floatingDebt / floatingAssets` is the same as before updating the floating debt.

**Comment by genesiscrew** [comment]
yeah makes sense
