### ISSUE TITLE
ether_sky - Updating maxFuturePools causes a significant shortage of rewards in the rewardsController.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-interest-rate-model-judging#146]
ether_sky

medium

# Updating maxFuturePools causes a significant shortage of rewards in the rewardsController.

## Vulnerability Detail
As noted in the comments below, we may need to reduce the value of `maxFuturePools`.
```solidity
/// @notice Sets the protocol's max future pools for fixed borrowing and lending.
/// @dev If value is decreased, VALID maturities will become NOT_READY.
/// @param futurePools number of pools to be active at the same time.
function setMaxFuturePools(uint8 futurePools) public onlyRole(DEFAULT_ADMIN_ROLE) {
  maxFuturePools = futurePools;
  emit MaxFuturePoolsSet(futurePools);
}
```
Let's take an example.
Initially, the `maxFuturePools` is set to `6`.
`BOB` `borrows` `1 ether` from a `fixed rate pool` at `4 weeks maturity`.
`ALICE` `borrows` `1 ether` from the same `fixed rate pool`.
`ALICE` then `borrows` an additional `20 ether` from a `fixed rate pool` at `24 weeks maturity` and this is possible.

The `admin` then changes `maxFuturePools` to `3`.
At the current time, which is at `11 weeks`, `BOB` decides to `claim` his `rewards` so we need to calculate the `total borrow shares` for distributing the `rewards`.
However, due to the `maxFuturePools` is `3`, only `fixed rate pools` with `maturities` up to `20 weeks` can be considered. (`12 weeks`, `16 weeks`, `20 weeks`.)
```solidity
function previewAllocation(
  RewardData storage rewardData,
  Market market,
  uint256 deltaTime
) internal view returns (uint256 borrowIndex, uint256 depositIndex, uint256 newUndistributed) {
  TotalMarketBalance memory m;
  m.floatingDebt = market.floatingDebt();
  m.floatingAssets = market.floatingAssets();
  TimeVars memory t;
  t.start = rewardData.start;
  t.end = rewardData.end;
  {
    uint256 firstMaturity = t.start - (t.start % FixedLib.INTERVAL) + FixedLib.INTERVAL;
    uint256 maxMaturity = block.timestamp -
      (block.timestamp % FixedLib.INTERVAL) +
      (FixedLib.INTERVAL * market.maxFuturePools());  // @audit, 11 weeks - (11 weeks % 4 weeks) + (4 weeks * 3) = 20 weeks
    uint256 fixedDebt;
    for (uint256 maturity = firstMaturity; maturity <= maxMaturity; ) {
      (uint256 borrowed, ) = market.fixedPoolBalance(maturity);
      fixedDebt += borrowed;
      unchecked {
        maturity += FixedLib.INTERVAL;
      }
    }
    m.debt = m.floatingDebt + fixedDebt;
    m.fixedBorrowShares = market.previewRepay(fixedDebt);
  }
}
```
Consequently, the `fixed borrow shares` for the `pool` at `24 weeks maturity` are ignored since it's not ready yet.
The `rewardsIndex` is calculated based on the `fixed borrow shares` of `2 ether` (`1 ether` for `BOB` and `1 ether` for `ALICE` from the `fixed rate pool` at `4 weeks maturity`)

From `12 weeks`, the `fixed rate pool` at `24 weeks maturity` becomes ready, and `ALICE`'s `20 ether` `fixed borrow shares` are now eligible for `claiming rewards`.
Although these `fixed borrow shares` were initially skipped in the `rewardsIndex` calculation, they are now considered, resulting in a significantly larger available `rewards` for `ALICE` than expected.

Below log shows that this available `rewards` for `ALICE` become much larger than the actual `rewards balance`.
```solidity
Rewards balance for BOB after 11 weeks     ==>   916666636000000000000
Available rewards for ALICE after 11 weeks ==>   916666636000000000000
Available rewards for ALICE after 15 weeks ==>   15101659177000000000000
Available rewards token balance            ==>   3083333364000000000000
```
Please add below test to `RewardsController.t.sol`:
```solidity
function testSetMaxFuturePools() external {
  marketUSDC.setMaxFuturePools(6);

  vm.prank(ALICE);
  marketUSDC.approve(address(this), 100 ether);

  vm.prank(BOB);
  marketUSDC.approve(address(this), 100 ether);

  vm.prank(ALICE);
  auditor.enterMarket(marketUSDC);

  vm.prank(BOB);
  auditor.enterMarket(marketUSDC);

  marketUSDC.deposit(50 ether, ALICE);
  marketUSDC.deposit(50 ether, BOB);

  marketUSDC.borrowAtMaturity(4 weeks, 1 ether, 20 ether, ALICE, ALICE);
  marketUSDC.borrowAtMaturity(24 weeks, 20 ether, 40 ether, ALICE, ALICE);
  marketUSDC.borrowAtMaturity(4 weeks, 1 ether, 20 ether, BOB, BOB);

  marketUSDC.setMaxFuturePools(3);
  vm.warp(11 weeks);
  
  vm.prank(BOB);
  rewardsController.claimAll(BOB);
  console2.log("Rewards balance for BOB after 11 weeks     ==>  ", opRewardAsset.balanceOf(BOB));
  console2.log("Available rewards for ALICE after 11 weeks ==>  ", rewardsController.allClaimable(ALICE, opRewardAsset));

  vm.warp(15 weeks);
  console2.log("Available rewards for ALICE after 15 weeks ==>  ", rewardsController.allClaimable(ALICE, opRewardAsset));
  console2.log("Available rewards token balance            ==>  ", opRewardAsset.balanceOf(address(rewardsController)));
}
```
## Code Snippet
https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/8f6ef1b0868d3ea3a98a5ab7e8b3a164857681d7/protocol/contracts/Market.sol#L1093-L1099
https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/8f6ef1b0868d3ea3a98a5ab7e8b3a164857681d7/protocol/contracts/RewardsController.sol#L482-L492
## Tool used

Manual Review

**Comment by etherSky111** [comment]
Escalate

I think this issue should be medium.
The `admin` can change `maxFuturePools` using below function.
```solidity
/// @notice Sets the protocol's max future pools for fixed borrowing and lending.
/// @dev If value is decreased, VALID maturities will become NOT_READY.
/// @param futurePools number of pools to be active at the same time.
function setMaxFuturePools(uint8 futurePools) public onlyRole(DEFAULT_ADMIN_ROLE) {
  maxFuturePools = futurePools;
  emit MaxFuturePoolsSet(futurePools);
}
```
Based on the comments, we know that when this value decreases, the valid `maturities` will change to `NOT_READY` status. 
However, this has nothing to do with `rewards distribution`.
In other words, this should not affect the `rewards distribution`.

If you observe the impact of this report, you'll find that it becomes significant. 
We should take this into account when changing the `maxFuturePools`.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I think this issue should be medium.
> The `admin` can change `maxFuturePools` using below function.
> ```solidity
> /// @notice Sets the protocol's max future pools for fixed borrowing and lending.
> /// @dev If value is decreased, VALID maturities will become NOT_READY.
> /// @param futurePools number of pools to be active at the same time.
> function setMaxFuturePools(uint8 futurePools) public onlyRole(DEFAULT_ADMIN_ROLE) {
>   maxFuturePools = futurePools;
>   emit MaxFuturePoolsSet(futurePools);
> }
> ```
> Based on the comments, we know that when this value decreases, the valid `maturities` will change to `NOT_READY` status. 
> However, this has nothing to do with `rewards distribution`.
> In other words, this should not affect the `rewards distribution`.
> 
> If you observe the impact of this report, you'll find that it becomes significant. 
> We should take this into account when changing the `maxFuturePools`.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by santipu03** [comment]
If the rewards distribution mechanism is based on the valid maturities and some maturities change to `NOT_READY`, it's implied that the rewards distribution will be disrupted. I think the code comment clearly states that `maxFuturePools` shouldn't be decreased, but it'd be impossible for the devs to explicitly state EVERY possible risk of decreasing `maxFuturePools` in the comments.

**Comment by etherSky111** [comment]
What are the comments from sponsor side?

Of course it's okay for me that this remain as invalid.
However, I want sponsor team to consider this issue to avoid unexpected outcome(high impact).

**Comment by santipu03** [comment]
Sometimes the sponsors don't take a look at excluded issues. I can say that in this judging process, the sponsors have been extremely busy on other things so there are not many comments from them.

**Comment by etherSky111** [comment]
Due to the impact is really high, I hope that lead of judge will take a look at this and respect his decision.

**Comment by etherSky111** [comment]
Hi @santichez , I hope you will check this issue please.

Maybe it doesn't require a specific fix, you need to consider this when reduce `maxFuturePools`.

**Comment by cvetanovv** [comment]
This issue falls into the Known issue category. 

Recently, there have been updates to the **Hierarchy of truth** [documentation](https://docs.sherlock.xyz/audits/judging/judging#iii.-sherlocks-standards), and now we consider "CODE COMMENTS" to be a source of truth. 

This means that we will take [this](https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/8f6ef1b0868d3ea3a98a5ab7e8b3a164857681d7/protocol/contracts/Market.sol#L1094) code comment as a known issue and that the protocol is aware of the consequences when the value is decreased.

Planning to reject the escalation and leave the issue as is.

**Comment by santichez** [comment]
@etherSky111 Sorry for the delay. I agree with @cvetanovv .
The protocol team is aware and since there is no reason to decrease the maximum number of future pools, this won't be done under any circumstance.
I can't remember now, but the team knows that there are other unexpected implications if the value is decreased, not only affecting distribution of rewards.

**Comment by etherSky111** [comment]
Hi @cvetanovv , thanks for your reviewing.

I totally agree with you.
However what about this issue #132?
If the `source of truth` is important, then in this issue there is a conflict between documentation and implementation.
Of course, I didn't escalate this issue.
Hope you will review this issue simply.

@santichez , could you please check #132?
It's totally okay for me you sponsor team just realize this issue.

Not sure whether this is intended and wrong description in the documentation.

**Comment by cvetanovv** [comment]
I reviewed this issue again and would like to add that my previous comment is invalid because this audit started before the rule changes. Code comments were not taken into consideration then.

However, this will not change the severity of the issue because the admin is TRUSTED, and it is his responsibility to handle the function correctly.

Regarding #132, I see no impact at all, so it is correctly invalid. Keep in mind that for future contests, problems similar to #132 may be valid Medium if they break restrictions or expected functionality described in the readme, even if they have no impact. This is because of the rule changes: 

> The protocol team can use the README (and only the README) to define language that indicates the codebase's restrictions and/or expected functionality. Issues that break these statements, irrespective of whether the impact is low/unknown, will be assigned Medium severity. 

I stand by my initial decision to reject the escalation.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [etherSky111](https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/146/#issuecomment-2117438279): rejected
