### ISSUE TITLE
Topmark - Wrong Implementation of Natural Utilization Rate Which Will Break Protocol Normal Functionality as Against Protocol Math Paper

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-interest-rate-model-judging#153]
Topmark

medium

# Wrong Implementation of Natural Utilization Rate Which Will Break Protocol Normal Functionality as Against Protocol Math Paper

## Summary
Wrong Implementation of Natural Utilization Rate Which Will Break Protocol Normal Functionality as Against Protocol Math Paper
## Vulnerability Detail
```solidity
  constructor(Parameters memory p, Market market_) {
    assert(
      p.minRate > 0 &&
        p.naturalRate > 0 &&
        p.maxUtilization > 1e18 &&
        p.naturalUtilization > 0 &&
>>>        p.naturalUtilization < 1e18 &&   ❌
        p.growthSpeed > 0 &&
        p.sigmoidSpeed > 0 &&
        p.spreadFactor > 0 &&
        p.maturitySpeed > 0 &&
        p.maxRate > 0 &&
        p.maxRate <= 15_000e16
    );

   ...
  }
```
The code above from the InterestRateModel contract shows how Parameters is validated in the contract, the parameters value are correctly validated as expected from documentation description except one variable i.e p.naturalUtilization which is noted from the pointer. The current validation does not put into consideration when naturalUtilization is exactly equal 1e18 which creates a gap in the protocol. 
A look at the protocol shows that Interest rates are determined based on the credit utilization rate of each Fixed Rate Pool. but if 1e18 is not added it means Dos when a 100% utilization is needed for interaction. To prove this issue report a look at the Protocol Math Paper at  https://docs.exact.ly/resources/math-paper#id-4.1.-borrowing-assets-at-fixed-rates it clearly states that
"where Ub​ conceptually represents the utilization level at the boundary between a region of normal interest rates (U≤Ub​) and a region of leveraged interest rates (U>Ub​)."
![image](https://github.com/sherlock-audit/2024-04-interest-rate-model-topmark1/assets/107555863/57094452-773d-4156-838f-40bae999e0b5)
which means a normal utilization interest (U) is expected to be less than or equal Ub
And it was also noted later in the documentation in that same section 4.1.1 that "for pratical reasons we will also choose Ub=1." meaning Ub is also correctly equal 1 which can also be represented as 1e18 in the contract, instead of the contract corectly implementing the code as U <= Ub (1e18) protocol wrongly used U < Ub (1e18) therefore cauing Dos when U is exactly equal 1e18
![image](https://github.com/sherlock-audit/2024-04-interest-rate-model-topmark1/assets/107555863/9acf6355-baab-48b6-a763-9c753e5ba640)
## Impact
Wrong Implementation of Natural Utilization Rate Which Will Break Protocol Normal Functionality as Against Protocol Math Paper which would cause Dos when expected natural Utilization rate for contract interaction is suppose to be exactly 1e18 in the Exactly Protocol!
## Code Snippet
https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/InterestRateModel.sol#L54

## Tool used

Manual Review

## Recommendation
The mitigation to this issue is straight forward and involves validating naturalUtilization to be <= 1e18 as described in doc instead of < 1e18 as implemented in protocol as adjusted below
```solidity
  constructor(Parameters memory p, Market market_) {
    assert(
      p.minRate > 0 &&
        p.naturalRate > 0 &&
        p.maxUtilization > 1e18 &&
        p.naturalUtilization > 0 &&
---        p.naturalUtilization < 1e18 &&   
+++        p.naturalUtilization <= 1e18 &&   
        p.growthSpeed > 0 &&
        p.sigmoidSpeed > 0 &&
        p.spreadFactor > 0 &&
        p.maturitySpeed > 0 &&
        p.maxRate > 0 &&
        p.maxRate <= 15_000e16
    );

   ...
  }
```

**Comment by Topmark1** [comment]
This report is not about it being a trusted role or possibility of inputting wrong value but this report is about the fact that this trusted role can't input a value that is expected to be allowed as input i.e p.naturalUtilization of 1e18 as described in report, which is a form of Denial of Service to this suppose trusted caller as you mentioned

**Comment by santipu03** [comment]
The issue is still low severity because it doesn't have any real impact. In the scenario where the admins try to deploy the contract with a natural utilization of 1e18, the transaction would fail and the mistake would be easily spotted. Then another contract would have been deployed with the fix, solving the issue. 

Even if we consider this issue a DoS, it can't be considered more than low severity according to the Sherlock rules:

> Could Denial-of-Service (DOS), griefing, or locking of contracts count as a Medium (or High) issue? DoS has two separate scores on which it can become an issue:
>1. The issue causes locking of funds for users for more than a week.
>2. The issue impacts the availability of time-sensitive functions (...)
