### ISSUE TITLE
bin2chen - assetPrice() BASE_FEED not scaled to 18-digit decimals

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-interest-rate-model-judging#75]
bin2chen

high

# assetPrice() BASE_FEED not scaled to 18-digit decimals

## Summary
in `assetPrice()`, if `BASE_FEED` returns `basePrice` directly.
But `basePrice` may not be `18-digit decimals`, such as `usdc`.
Returning the wrong decimals will result in the wrong asset valuation

## Vulnerability Detail
`Auditor.assetPrice()` is used to get the price of the asset, which needs to be scaled to`18-digit decimals`
The code implementation is as follows:
```solidity
  function assetPrice(IPriceFeed priceFeed) public view returns (uint256) {
@>  if (address(priceFeed) == BASE_FEED) return basePrice;

    int256 price = priceFeed.latestAnswer();
    if (price <= 0) revert InvalidPrice();
    return uint256(price) * baseFactor;
  }
```

We can see in the code above. If it wasn't `BASE_FEED`, it would have `scaled to 18-digit decimals` of the price
> `uint256(price) * baseFactor`

If it is `BASE_FEED`, it returns `basePrice` directly.
>if (address(priceFeed) == BASE_FEED) return basePrice;

But `basePrice` is in `priceDecimals_` not necessarily in `18-digit decimals` , e.g. `USDC`.
```solidity
contract Auditor is Initializable, AccessControlUpgradeable {
...
  constructor(uint256 priceDecimals_) {
    priceDecimals = priceDecimals_;
    baseFactor = 10 ** (18 - priceDecimals_);
@>  basePrice = 10 ** priceDecimals_;

    _disableInitializers();
  }

```

## Impact

Incorrect decimals of the price will result in an undervaluation of the collateral or debt.
If the asset is a debt it will be illegally borrowed against a large amount of assets, and if the asset is collateral it will result in early liquidation.

## Code Snippet
https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Auditor.sol#L327
## Tool used

Manual Review

## Recommendation
```diff
  function assetPrice(IPriceFeed priceFeed) public view returns (uint256) {
-   if (address(priceFeed) == BASE_FEED) return basePrice;
+   if (address(priceFeed) == BASE_FEED) return basePrice * baseFactor;

    int256 price = priceFeed.latestAnswer();
    if (price <= 0) revert InvalidPrice();
    return uint256(price) * baseFactor;
  }
```

**Comment by bin2chen66** [comment]
Escalate
>This issue is invalid because the owner is TRUSTED so it's assumed the correct Chainlink feed will be enabled even when using stablecoins (USDC/USD).

I don't quite understand what this means.
The logic of the code is like this, it's not a relationship of `TRUSTED` or not
Or where the document say this `BASE_FEED` is useless or the admin won't use BASE_FEED?
So what is all this code for?
```solidity
@> /// @notice Address that a market should have as price feed to consider as base price and avoid external price call.
  address public constant BASE_FEED = 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE;

  function enableMarket(
    Market market,
    IPriceFeed priceFeed,
    uint128 adjustFactor
  ) external onlyRole(DEFAULT_ADMIN_ROLE) {
    if (market.auditor() != this) revert AuditorMismatch();
    if (markets[market].isListed) revert MarketAlreadyListed();
@>  if (address(priceFeed) != BASE_FEED && priceFeed.decimals() != priceDecimals) revert InvalidPriceFeed();

  function assetPrice(IPriceFeed priceFeed) public view returns (uint256) {
@>   if (address(priceFeed) == BASE_FEED) return basePrice;
....


```

Please take a look again, thanks

**Comment by santipu03** [comment]
From my understanding, `BASE_FEED` will be used by the admins when they want to enable a market with a price feed that will always return a price of `basePrice`. Given that the admins know how the code works, I believe they will only set `BASE_FEED` for assets where they always need that `basePrice` so there's no need to scale that value.

**Comment by bin2chen66** [comment]
> From my understanding, `BASE_FEED` will be used by the admins when they want to enable a market with a price feed that will always return a price of `basePrice`. ****Given that the admins know how the code works***, I believe they will only set `BASE_FEED` for assets where they always need that `basePrice` so there's no need to scale that value.

>****Given that the admins know how the code works***

This is the biggest point of audit, the actual code does not run as the administrator expects, `Code is law`.

According to the definition of code
```solidity
  /// @notice Gets the asset price of a price feed.
  /// @dev If Chainlink's asset price is <= 0 the call is reverted.
  /// @param priceFeed address of Chainlink's Price Feed aggregator used to query the asset price.
@>/// @return The price of the asset scaled to 18-digit decimals.
  function assetPrice(IPriceFeed priceFeed) public view returns (uint256) {
@>  if (address(priceFeed) == BASE_FEED) return basePrice;

    int256 price = priceFeed.latestAnswer();
    if (price <= 0) revert InvalidPrice();
    return uint256(price) * baseFactor;
  }
```

This requires `scaled to 18-digit decimals.`
But currently if `BASE_FEED` doesn't do this
Only the suggested `if (address(priceFeed) == BASE_FEED) return basePrice * baseFactor;` is expected.

**Comment by santipu03** [comment]
@santichez What is your stance on this issue? For what reasons should you use the `BASE_FEED`?

**Comment by MehdiKarimi81** [comment]
This is also duplicate of this issue : #106

**Comment by santichez** [comment]
`BASE_FEED` will always be used for `18 decimals` values, i.e. ETH value -> 1 ether, and will never contain non-native prices.

**Comment by cvetanovv** [comment]
Since the sponsor confirmed that BASE_FEED will always be used for 18 decimal values, this issue is invalid.

Planning to reject the escalation and leave the issue as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [bin2chen66](https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/75/#issuecomment-2117286060): rejected
