### ISSUE TITLE
alymurtazamemon - handle the return value of `latestAnswer` price feed function

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-04-interest-rate-model-judging#94]
alymurtazamemon

medium

# handle the return value of `latestAnswer` price feed function

## Summary

Firstly, the `latestAnswer` function is deprecated, yet the protocol still intends to use it. In this case, it should handle the return value of this function correctly.

One notable behavior of this function to check for is that it can return a price of zero.

## Vulnerability Detail

According to the `AggregatorProxy.sol` contract, this function does not error if no answer has been reached; it will simply return 0, leading to potential issues such as multiplying with other price feed values and resulting in zero or causing reverts when dividing by zero.

```solidity
function assetPrice(IPriceFeed priceFeed) public view returns (uint256) {
if (address(priceFeed) == BASE_FEED) return basePrice;

int256 price = priceFeed.latestAnswer();

if (price <= 0) revert InvalidPrice();

return uint256(price) * baseFactor;
}
```
In this function, this condition is checked, but developers fail to validate it in other sections, as mentioned in the code snippets.

## Impact

The impact will be that the oracle-dependent functions will either operate with a zero returned value or revert in cases where the `latestAnswer()` function fails to retrieve an answer and instead returns 0.

## Code Snippet

[PriceFeedDouble.sol - line 28](https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/8f6ef1b0868d3ea3a98a5ab7e8b3a164857681d7/protocol/contracts/PriceFeedDouble.sol#L28)

[PriceFeedPool.sol - line 36](https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/8f6ef1b0868d3ea3a98a5ab7e8b3a164857681d7/protocol/contracts/PriceFeedPool.sol#L36)

[PriceFeedWrapper.sol - line 31](https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/8f6ef1b0868d3ea3a98a5ab7e8b3a164857681d7/protocol/contracts/PriceFeedWrapper.sol#L31)

## Tool used

Manual Review

## Recommendation

Add this condition to all locations.

```solidity
if(price > 0) {
    return price;
} else {
    // `latestAnswer` is a deprecated method to read prices, yet still used in the wild.
    // It can return zero under certain circumstances, so integrations should handle this case.
    // Either with revert, call propietary fallback oracle, fetch from another 3rd-party oracle, etc.
}
```

Duplicate of #235

**Comment by santipu03** [comment]
This issue has been duplicated with #235 because the root cause is misbehavior (return 0 or stop working) in the `latestAnswer` function from the Chainlink side. So, as I stated in the primary issue, IMO it should be invalid considering this section of the README:

> Please list any known issues/acceptable risks that should not result in a valid finding.
We trust Chainlink, and no liveness checks are performed while retrieving Oracle data.

However, as I admitted in #235, it's up to interpretation.
